apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator-polr-adapter
spec:
  interval: 30m
  chart:
    spec:
      chart: trivy-operator-polr-adapter
      version: "0.10.0"
      sourceRef:
        kind: HelmRepository
        name: trivy-operator-polr-adapter
        namespace: trivy-adapter
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
    

