apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gatekeeper-system
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml

configMapGenerator:
- name: values
  files:
  - values.yaml

configurations:
- kustomizeconfig.yaml