apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
spec:
  interval: 30m
  chart:
    spec:
      chart: gatekeeper
      version: "3.18.2"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: gatekeeper-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
    

