apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: duckdns-wildcard-cert
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    creationPolicy: Owner
  data:
  - secretKey: tls.crt
    remoteRef:
      key: /k8s/change/me/cert
  - secretKey: tls.key
    remoteRef:
      key: /k8s/change/me/key