apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: duckdns-cert
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    template:
      type: kubernetes.io/tls
  data:
  - secretKey: tls.crt
    remoteRef:
      key: tls/change.me/cert
      decodingStrategy: Base64
  - secretKey: tls.key
    remoteRef:
      key: tls/change.me/key
      decodingStrategy: Base64