apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/duckdns-wildcard-cert-ext/

patches:
- patch: |-
    - op: replace
      path: /spec/data/0/remoteRef/key
      value: /k8s/local/jklocal.duckdns.org/cert
    - op: replace
      path: /spec/data/1/remoteRef/key
      value: /k8s/local/jklocal.duckdns.org/key
  target:
    group: external-secrets.io
    version: v1beta1
    kind: ExternalSecret
    name: duckdns-wildcard-cert