apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: policy-reporter
spec:
  interval: 30m
  chart:
    spec:
      chart: policy-reporter
      version: "3.0.4"
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: policy-reporter
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
    

