apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secretsmanager
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      identityURL: https://identity.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-access-token
            namespace: external-secrets
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      caProvider:
        type: Secret
        namespace: cert-manager
        name: ca-root-secret
        key: ca.crt
      organizationID: 0d0b9f7e-5edf-42c9-a76d-b02701126382
      projectID: 0ce416b9-7974-4c02-9fb8-b43a011c5f6b