version: '3'

dotenv: [".env"]

vars:
  DOCS_URL: https://taskfile.dev/usage/

tasks:

# Task

  docs:
    desc: Open the Taskfile docs
    silent: true
    cmds:
    - task: docs_linux
    - task: docs_mac
    - task: docs_windows

  docs_linux:
    internal: true
    platforms: [linux]
    silent: true
    cmds:
    - xdg-open {{.DOCS_URL}}
    - exit 0

  docs_mac:
    internal: true
    platforms: [darwin]
    silent: true
    cmds:
    - open {{.DOCS_URL}}

  docs_windows:
    internal: true
    platforms: [windows]
    silent: true
    cmds:
    - start {{.DOCS_URL}}

  hello:
    cmds:
      - echo "Hello from task"

# Kubernetes

  # apply kustomize folder
  # remove kustomize folder
  # upgrade
  # token for dashboard

# Terraform

  init:
    cmds:
    - terraform init
    desc: Initialise terraform
    dir: '{{ .ROOT_DIR }}/terraform'
    env:
      TF_WORKSPACE: "{{.CLUSTER}}"
    requires:
      vars: [ TF_TOKEN_app_terraform_io, CLUSTER ]

  plan:
    cmds:
    - terraform fmt *.tf
    - tflint
    - terraform plan {{.DESTROY}}-var cluster={{.CLUSTER}} -input=false -out=tfplan
    desc: Run terraform plan for a cluster
    dir: '{{ .ROOT_DIR }}/terraform'
    env:
      TF_WORKSPACE: "{{.CLUSTER}}"
    requires:
      vars: [ TF_TOKEN_app_terraform_io, TF_VAR_akeyless_id, TF_VAR_akeyless_key, CLUSTER ]
    vars:
      DESTROY: '{{.DESTROY | default "" }}'

  build:
    cmds:
    - task: init
    - task: plan
    - terraform apply tfplan
    desc: Build a cluster with terraform
    dir: '{{ .ROOT_DIR }}/terraform'
    env:
      TF_WORKSPACE: "{{.CLUSTER}}"
    requires:
      vars: [ TF_TOKEN_app_terraform_io, TF_VAR_akeyless_id, TF_VAR_akeyless_key, CLUSTER ]

  destroy:
    cmds:
    - task: init
    - task: plan
      vars: { DESTROY: '-destroy ' }
    - terraform apply tfplan
    desc: Destroy a cluster with terraform
    dir: '{{ .ROOT_DIR }}/terraform'
    env:
      TF_WORKSPACE: "{{.CLUSTER}}"
    requires:
      vars: [ TF_TOKEN_app_terraform_io, TF_VAR_akeyless_id, TF_VAR_akeyless_key, CLUSTER ]