version: '3'

dotenv: [".env"]

tasks:
  hello:
    cmds:
      - echo "Hello from task"


  tf-create-alpha-local:
    desc: deploy alpha cluster to local host with terraform
    aliases:
      - tf-a-l 
    cmds:
      - task: terraform-plan
        vars: { CLUSTER: 'alpha', HOST: 'local' }

  tf-destroy-alpha-local:
    desc: destroy alpha cluster on local host with terraform
    aliases:
      - tfd-a-l 
    cmds:
      - task: terraform-plan
        vars: { CLUSTER: 'alpha', HOST: 'local', DESTROY: '-destroy ' }

  tf-create-beta-local2:
    desc: deploy beta cluster to local2 host with terraform
    aliases:
      - tf-b-2 
    cmds:
      - task: terraform-plan
        vars: { CLUSTER: 'beta', HOST: 'local2' }

  tf-destroy-beta-local2:
    desc: destroy beta cluster on local2 host with terraform
    aliases:
      - tfd-b-2
    cmds:
      - task: terraform-plan
        vars: { CLUSTER: 'beta', HOST: 'local2', DESTROY: '-destroy ' }
      

  terraform-plan:
    internal: true
    vars:
      HOST: '{{.HOST}}'
      DESTROY: '{{.DESTROY | default "" }}'
    dir: '{{ .ROOT_DIR }}/terraform'
    cmds:
    - terraform init
    - terraform plan {{.DESTROY}}-var cluster={{.CLUSTER}} -var host={{.HOST}} -input=false -out=tfplan
    - terraform apply tfplan
    env:
      TF_WORKSPACE: '{{.HOST}}'