version: '3'

dotenv: [".env"]

tasks:
  hello:
    cmd: echo "Hello from task"
    desc: Hello World
    silent: true
  list:
    cmd: task --list
    desc: List all tasks
    silent: true
  terraform:
    cmds:
    - terraform fmt --recursive
    - tflint
    - terraform init -upgrade
    - terraform {{ .ACTION }}
    desc: Plan/Apply/Destroy cluster with Terraform
    dir: '{{ .ROOT_DIR }}/terraform'
    env:
      TF_WORKSPACE: "{{ .HOST | upper }}"
      TF_TOKEN_app_terraform_io: "{{ .TF_TOKEN_app_terraform_io }}"
    requires:
      vars: [ HOST, TF_TOKEN_app_terraform_io ]
    silent: true
    vars:
      ACTION: '{{ .ACTION | default "plan" }}'