apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/duckdns-wildcard-cert-cm/

patches:
- patch: |-
    - op: replace
      path: /spec/commonName
      value: "*.jklocal.duckdns.org"
    - op: replace
      path: /spec/dnsNames
      value: 
      - "*.jklocal.duckdns.org"
  target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: duckdns-wildcard-cert