apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/kyverno-policies

patches:
- patch: |-
    $patch: delete
    apiVersion: kyverno.io/v1
    kind: ClusterPolicy
    metadata:
      name: application-prevent-default-project