- Containers:
  - Artifact Hub:
      icon: artifacthub
      href: https://artifacthub.io/
      description: Helm chart registry
- Databases:
  - Neon:
      icon: neon-tech
      href: https://console.neon.tech/
      description: PostgreSQL DBaaS provider