apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: test
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  data:
  - secretKey: test
    remoteRef:
      key: test