apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubetail
spec:
  interval: 30m
  chart:
    spec:
      chart: kubetail
      version: "0.9.6"
      sourceRef:
        kind: HelmRepository
        name: kubetail
        namespace: kubetail
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
    

