replicaCount: 1
ingress:
  enabled: "true"
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
  - host: hello.jklocal.duckdns.org
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls:
  - hosts: 
    - "*.jklocal.duckdns.org"