replicaCount: 1
ingress:
  enabled: "true"
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: duckdns-letsencrypt-prod
  hosts:
  - host: hello.jklocal.duckdns.org
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls:
  - hosts: 
    - hello.jklocal.duckdns.org
    secretName: hello-cert