apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../overlay/cert-manager.yaml
- ../../overlay/cert-manager-ca.yaml
- ../../overlay/echo/dev.yaml
- ../../overlay/external-secrets.yaml
- ../../overlay/external-secrets-store.yaml
- ../../overlay/gateway-api.yaml
- ../../overlay/gateway/alpha.yaml
- ../../overlay/headlamp/dev.yaml
- ../../overlay/homepage/dev.yaml
- ../../overlay/longhorn/dev.yaml
- ../../overlay/metallb.yaml
- ../../overlay/metallb-pool/mu.yaml
- ../../overlay/metrics-server.yaml
- ../../overlay/nginx-gateway-fabric.yaml
- ../../overlay/test-secret.yaml
