apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../infrastructure/base/external-secrets-store/
- ../../../../infrastructure/local/duckdns-wildcard-cert-ext/
- ../../../../infrastructure/base/ingress-nginx/

