apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: charts
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - appName: hello
          namespace: hello
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: bootstrap
      source:
        repoURL: git@github.com:mprzygrodzki/aws-eks-bootstrap.git
        targetRevision: HEAD
        path: "charts/{{appName}}"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - "values.yaml"
          - "../../values/{{name}}/{{appName}}/values.yaml"
      destination:
        # Default base cluster
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true