apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/flux-capacitor/

patches:
- patch: |-
    - op: replace
      path: /spec/tls/0/hosts
      value: 
      - "*.jklocal.duckdns.org"
    - op: replace
      path: /spec/rules/0/host
      value: flux.jklocal.duckdns.org
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: capacitor