apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: charts
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - appName: hello
        branch: main
        chart: hello
        environment: local
        namespace: hello
        repository: https://cloudecho.github.io/charts/
        version: 0.1.2
      - appName: kubernetes-dashboard
        branch: main
        chart: kubernetes-dashboard
        environment: base
        namespace: kubernetes-dashboard
        repository: https://kubernetes.github.io/dashboard/
        version: 7.10.4
      - appName: kubetail
        branch: main
        chart: kubetail
        environment: local
        namespace: kubetail
        repository: https://kubetail-org.github.io/helm-charts/
        version: 0.9.6
      - appName: policy-reporter
        branch: main
        chart: policy-reporter
        environment: local
        namespace: policy-reporter
        repository: https://kyverno.github.io/policy-reporter
        version: 3.0.4
  template:
    metadata:
      name: '{{appName}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;..
    spec:
      project: default
      sources:
      - repoURL: '{{repository}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
          - $self/apps/{{environment}}/{{appName}}/values.yaml
          ignoreMissingValueFiles: true
      - repoURL: https://github.com/jamesdkelly88/kubernetes-lab.git
        targetRevision: '{{ branch }}'
        ref: self
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true

