apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-manifests
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - name: kyverno-policies
        environment: alpha
        branch: main
      - name: external-secrets-store
        environment: base
        branch: main
      - name: duckdns-wildcard-cert-ext
        environment: local
        branch: main
  template:
    metadata:
      name: '{{name}}'
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    spec:
      project: default
      source:
        repoURL: https://github.com/jamesdkelly88/kubernetes-lab.git
        targetRevision: '{{ branch }}'
        path: infrastructure/{{ environment }}/{{ name }}
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - ApplyOutOfSyncOnly=true

