apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kyverno
spec:
  interval: 30m
  chart:
    spec:
      chart: kyverno
      version: "3.3.7"
      sourceRef:
        kind: HelmRepository
        name: kyverno
        namespace: kyverno
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
    

