apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base/

patches:
- path: ip-patch.yaml
  target:
    group: metallb.io
    version: v1beta1
    kind: IPAddressPool
    name: default-pool