apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy
spec:
  interval: 30m
  chart:
    spec:
      chart: trivy-operator
      version: "0.27.0"
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: trivy-system
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
    

