apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/cert-manager-duckdns/

configMapGenerator:
- name: duckdns-values
  behavior: replace
  files:
  - values.yaml

configurations:
- kustomizeconfig.yaml