apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-charts
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - appName: external-secrets
        branch: main
        chart: external-secrets
        environment: base
        namespace: external-secrets
        replace: "false"
        repository: https://charts.external-secrets.io
        serverside: "false"
        version: 0.15.0
      - appName: openebs
        branch: main
        chart: openebs
        environment: base
        namespace: openebs
        replace: "false"
        repository: https://openebs.github.io/openebs
        serverside: "false"
        version: 4.2.0
      - appName: ingress-nginx
        branch: main
        chart: ingress-nginx
        environment: base
        namespace: ingress-nginx
        replace: "false"
        repository: https://kubernetes.github.io/ingress-nginx
        serverside: "false"
        version: 4.12.1
      - appName: trivy-operator
        branch: main
        chart: trivy-operator
        environment: base
        namespace: trivy-system
        replace: "false"
        repository: https://aquasecurity.github.io/helm-charts/
        serverside: "false"
        version: 0.27.0
      - appName: trivy-polr-adapter
        branch: main
        chart: trivy-operator-polr-adapter
        environment: base
        namespace: trivy-adapter
        replace: "false"
        repository: https://fjogeleit.github.io/trivy-operator-polr-adapter
        serverside: "false"
        version: 0.10.0
  template:
    metadata:
      name: '{{appName}}'
      annotations:
        argocd.argoproj.io/manifest-generate-paths: .;..
    spec:
      project: default
      sources:
      - repoURL: '{{repository}}'
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          valueFiles:
          - $self/infrastructure/{{environment}}/{{appName}}/values.yaml
          ignoreMissingValueFiles: true
      - repoURL: https://github.com/jamesdkelly88/kubernetes-lab.git
        targetRevision: '{{ branch }}'
        ref: self
      destination:
        name: in-cluster
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - Replace={{replace}}
        - ServerSideApply={{serverside}}

