apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: "2.0.2"
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: homepage
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
    

