apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../overlay/cert-manager.yaml
- ../../overlay/cert-manager-ca.yaml
- ../../overlay/echo.yaml
- ../../overlay/external-secrets.yaml
- ../../overlay/external-secrets-store.yaml
- ../../overlay/gateway-api.yaml
- ../../overlay/metallb.yaml
- ../../overlay/nginx-gateway-fabric.yaml
- ../../overlay/test-secret.yaml
