apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../overlay/cert-manager.yaml
- ../../overlay/echo.yaml
- ../../overlay/external-secrets.yaml
- ../../overlay/external-secrets-store.yaml
