apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homer

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
- name: config
  namespace: homer
  behavior: create
  files:
  - files/config.yml

  
