controller:
  extraArgs:
    default-ssl-certificate: cert-manager/duckdns-wildcard-cert
  hostPort:
    enabled: true
  ingressClassResource:
    default: true
  service:
    type: NodePort
  watchIngressWithoutClass: true