apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/kubetail/

configMapGenerator:
- name: values
  behavior: replace
  files:
  - values.yaml

configurations:
- kustomizeconfig.yaml