plugin:
  kyverno:
    enabled: true
  trivy:
    enabled: true
ui:
  enabled: true
  displayMode: dark
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: kyverno.jklocal.duckdns.org
        paths:
        - path: "/"
          pathType: ImplementationSpecific
    tls:
    - hosts: 
      - "*.jklocal.duckdns.org"