apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: duckdns
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless
  target:
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: /k8s/common/duckdns