apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: duckdns-wildcard-cert
spec:
  secretName: duckdns-wildcard-cert
  issuerRef: 
    kind: ClusterIssuer
    name: duckdns-letsencrypt-prod
  commonName: "change.me"
  dnsNames:
    - "change.me" 