apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hello
spec:
  interval: 30m
  chart:
    spec:
      chart: hello
      version: "0.1.2"
      sourceRef:
        kind: HelmRepository
        name: cloudecho
        namespace: hello
      interval: 12h
  valuesFrom:
    - kind: ConfigMap
      name: values
    

